# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complete_comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField()),
                ('comic_title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
                ('comic_cover', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comics', models.ManyToManyField(to='comics.complete_comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.profile')),
            ],
        ),
    ]
