# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_complete_comic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_comic',
            name='description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
